# Generated by Django 5.2.12 on 2026-05-09 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.CharField(max_length=36)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("tmdb", "The Movie Database"),
                            ("mal", "MyAnimeList"),
                            ("mangaupdates", "MangaUpdates"),
                            ("igdb", "Internet Game Database"),
                            ("openlibrary", "Open Library"),
                            ("hardcover", "Hardcover"),
                            ("comicvine", "Comic Vine"),
                            ("bgg", "BoardGameGeek"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("tv", "TV Show"),
                            ("season", "TV Season"),
                            ("episode", "Episode"),
                            ("movie", "Movie"),
                            ("anime", "Anime"),
                            ("manga", "Manga"),
                            ("game", "Game"),
                            ("book", "Book"),
                            ("comic", "Comic"),
                            ("boardgame", "Boardgame"),
                        ],
                        default="movie",
                        max_length=10,
                    ),
                ),
                ("title", models.TextField()),
                ("image", models.URLField()),
                ("season_number", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["media_id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("episode_number__isnull", True),
                            ("season_number__isnull", True),
                        ),
                        fields=("media_id", "source", "media_type"),
                        name="unique_item_without_season_episode",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("episode_number__isnull", True),
                            ("season_number__isnull", False),
                        ),
                        fields=("media_id", "source", "media_type", "season_number"),
                        name="unique_item_with_season",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("episode_number__isnull", False),
                            ("season_number__isnull", False),
                        ),
                        fields=(
                            "media_id",
                            "source",
                            "media_type",
                            "season_number",
                            "episode_number",
                        ),
                        name="unique_item_with_season_episode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("episode_number__isnull", True),
                                ("media_type", "season"),
                                ("season_number__isnull", False),
                            ),
                            models.Q(("media_type", "season"), _negated=True),
                            _connector="OR",
                        ),
                        name="season_number_required_for_season",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("episode_number__isnull", False),
                                ("media_type", "episode"),
                                ("season_number__isnull", False),
                            ),
                            models.Q(("media_type", "episode"), _negated=True),
                            _connector="OR",
                        ),
                        name="season_and_episode_required_for_episode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(
                                    ("media_type__in", ["season", "episode"]),
                                    _negated=True,
                                ),
                                ("episode_number__isnull", True),
                                ("season_number__isnull", True),
                            ),
                            ("media_type__in", ["season", "episode"]),
                            _connector="OR",
                        ),
                        name="no_season_episode_for_other_types",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "source__in",
                                [
                                    "tmdb",
                                    "mal",
                                    "mangaupdates",
                                    "igdb",
                                    "openlibrary",
                                    "hardcover",
                                    "comicvine",
                                    "bgg",
                                    "manual",
                                ],
                            )
                        ),
                        name="app_item_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "media_type__in",
                                [
                                    "tv",
                                    "season",
                                    "episode",
                                    "movie",
                                    "anime",
                                    "manga",
                                    "game",
                                    "book",
                                    "comic",
                                    "boardgame",
                                ],
                            )
                        ),
                        name="app_item_media_type_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BasicMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.item",
                    ),
                ),
                (
                    "related_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="app.season",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "related_season",
                    "item__episode_number",
                    "-end_date",
                    "-created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="TV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.DecimalValidator(3, 1),
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("In progress", "In Progress"),
                            ("Planning", "Planning"),
                            ("Paused", "Paused"),
                            ("Dropped", "Dropped"),
                        ],
                        default="Completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "item"],
            },
        ),
        migrations.AddField(
            model_name="season",
            name="related_tv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="app.tv",
            ),
        ),
        migrations.AddConstraint(
            model_name="tv",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="app_tv_unique_item_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("related_tv", "item"), name="app_season_unique_tv_item"
            ),
        ),
    ]
